services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: gaming-journal-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gaming_journal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  studio:
    image: oven/bun:latest
    container_name: gaming-journal-studio
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/gaming_journal
    ports:
      - "5555:51212"
    command: bunx prisma studio --browser none
    depends_on:
      - db

volumes:
  pgdata:
